In [1]:
import torch
import numpy as np


# PyTorch basics


In [2]:
x = torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 1.3452e-42],
        [0.0000e+00, 7.0065e-45, 0.0000e+00],
        [5.7089e+17, 5.7313e-43, 0.0000e+00],
        [0.0000e+00, 7.0065e-45, 0.0000e+00],
        [5.7093e+17, 5.7313e-43, 0.0000e+00]])


In [3]:
x = torch.rand(5,3)
x

tensor([[0.0108, 0.9216, 0.3071],
        [0.9267, 0.8003, 0.1544],
        [0.2170, 0.7339, 0.4461],
        [0.0778, 0.7432, 0.2693],
        [0.0191, 0.5264, 0.6987]])

In [4]:
x = torch.zeros(5,3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [7]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-0.8384, -0.9783, -0.0818],
        [-0.9400, -0.2646, -0.0966],
        [ 0.1025, -1.5031, -1.3615],
        [ 0.0896,  1.5227, -0.3770],
        [-0.7099,  0.7256, -0.1656]])

In [8]:
print(x.size)
print(x.size())

<built-in method size of Tensor object at 0x0000019961239288>
torch.Size([5, 3])


In [9]:
y = torch.rand(5,3)
y

tensor([[0.3168, 0.6398, 0.2417],
        [0.4726, 0.3644, 0.3918],
        [0.1625, 0.2840, 0.7286],
        [0.4607, 0.7288, 0.5561],
        [0.3915, 0.0191, 0.6764]])

In [10]:
print(x + y)

tensor([[-0.5216, -0.3384,  0.1599],
        [-0.4673,  0.0999,  0.2952],
        [ 0.2650, -1.2191, -0.6329],
        [ 0.5504,  2.2515,  0.1790],
        [-0.3184,  0.7447,  0.5108]])


In [11]:
result = torch.empty(5,3)
torch.add(x,y, out = result)
print(result)
y.add_(x)
#Any operation that mutates a tensor in-place is post-fixed with an _. 
#For example: x.copy_(y), x.t_(), will change x.
print(y)

tensor([[-0.5216, -0.3384,  0.1599],
        [-0.4673,  0.0999,  0.2952],
        [ 0.2650, -1.2191, -0.6329],
        [ 0.5504,  2.2515,  0.1790],
        [-0.3184,  0.7447,  0.5108]])
tensor([[-0.5216, -0.3384,  0.1599],
        [-0.4673,  0.0999,  0.2952],
        [ 0.2650, -1.2191, -0.6329],
        [ 0.5504,  2.2515,  0.1790],
        [-0.3184,  0.7447,  0.5108]])


In [12]:
#Resizing: If you want to resize/reshape tensor, you can use torch.view:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(z)
print(x.size(),y.size(), z.size())

tensor([[ 2.1045,  0.3963,  0.0170, -0.9129, -0.1726,  1.4411, -1.0357, -0.8146],
        [ 0.0257, -0.3906, -0.3194, -1.3292,  0.1731,  0.6121, -0.1650,  1.2890]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
x = torch.randn(1)
print(x)
print(x.item())
#100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, 
#https://pytorch.org/docs/stable/torch.html

tensor([-0.5432])
-0.5431690812110901


nupy bridge

In [23]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [24]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [25]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [27]:
#Converting NumPy Array to Torch Tensor
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1, out= a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors

In [28]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([0.4568], device='cuda:0')
tensor([0.4568], dtype=torch.float64)
